# Generated by Django 4.0 on 2023-12-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('monthly_income', models.IntegerField()),
                ('phone_number', models.IntegerField(max_length=15)),
                ('approved_limit', models.IntegerField()),
                ('current_debt', models.FloatField(default=0.0)),
                ('credit_score', models.IntegerField(default=0)),
            ],
        ),
    ]
